### ISSUE TITLE
notebooks downstream adaptation

### ISSUE THREAD

**Issue by rohanvarm** [graphcore-research/minimol#1]
I'm pretty sure I saw a notebook folder here, where has it gone? 

Thanks, this work is exciting

**Comment by blazejba** [comment]
Nicely spotted. The notebook is back in. Also, if you plan on using Minimol, make sure it uses the newest commit or minimol>=1.2 from PyPI, as we made some changes that improve the fingerprints. Let us know if you have any issues with installation as we are working on improving the UX.
