### ISSUE TITLE
Turning off featurizing_smiles tqdm in a Jupyter Notebook

### ISSUE THREAD

**Issue by leifsieben** [graphcore-research/minimol#5]
Thank you for the fantastic work! Really enjoying how fast training MiniMol is while crushing my benchmarks. 

I'm training MiniMol in a jupyter notebook where I use an ensemble of 10 models in an active learning setting, where I need to re-train the model a lot. For that reason, I get a lot of tqdm progress bars which I seemingly can't turn off globablly. Particularly the smiles featurizer `MiniMol()` which completely fills up my notebook output. 

Is there a way to supress the tqdm progress bars?

**Comment by blazejba** [comment]
Thank you! 

The following should suppress tqdm while processing molecules:
```
import os
from contextlib import redirect_stdout, redirect_stderr
from minimol import Minimol

featurizer = Minimol()
mols = [...]

with open(os.devnull, 'w') as fnull, redirect_stdout(fnull), redirect_stderr(fnull):
      embeddings = featurizer(mols)
```

**Comment by leifsieben** [comment]
Thank you so much!
